// Generated by scripts/record-git-fixtures.mjs with git version 2.43.0. Do not edit by hand.

export interface GitFixture {
  name: string;
  left: string;
  right: string;
  /** Recorded with git diff -w. */
  ignoreWhitespace: boolean;
  /**
   * The expected patch: git's output from the --- line on, without the function names after hunk headers. For -w
   * fixtures its context lines come from the left file, as toUnifiedDiff prints them (git takes them from the right).
   */
  patch: string;
  /** git's own output, where it differs from `patch` (the -w fixtures with a context line that differs). */
  git?: string;
}

export const GIT_FIXTURES: GitFixture[] = [
  {
    "name": "one changed line",
    "left": "alpha\nbeta\ngamma\n",
    "right": "alpha\nBETA\ngamma\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,3 +1,3 @@\n alpha\n-beta\n+BETA\n gamma\n"
  },
  {
    "name": "added at the start",
    "left": "b\nc\nd\ne\n",
    "right": "a\nb\nc\nd\ne\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,3 +1,4 @@\n+a\n b\n c\n d\n"
  },
  {
    "name": "added at the end",
    "left": "a\nb\nc\n",
    "right": "a\nb\nc\nd\ne\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,3 +1,5 @@\n a\n b\n c\n+d\n+e\n"
  },
  {
    "name": "removed at the start",
    "left": "a\nb\nc\nd\ne\n",
    "right": "c\nd\ne\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,5 +1,3 @@\n-a\n-b\n c\n d\n e\n"
  },
  {
    "name": "everything removed",
    "left": "a\nb\n",
    "right": "",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,2 +0,0 @@\n-a\n-b\n"
  },
  {
    "name": "from nothing",
    "left": "",
    "right": "a\nb\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -0,0 +1,2 @@\n+a\n+b\n"
  },
  {
    "name": "two distant changes make two hunks",
    "left": "line 1\nline 2\nline 3\nline 4\nline 5\nline 6\nline 7\nline 8\nline 9\nline 10\nline 11\nline 12\nline 13\nline 14\nline 15\nline 16\nline 17\nline 18\nline 19\nline 20\nline 21\nline 22\nline 23\nline 24\nline 25\nline 26\nline 27\nline 28\nline 29\nline 30\n",
    "right": "line 1\nline 2\nchanged 3\nline 4\nline 5\nline 6\nline 7\nline 8\nline 9\nline 10\nline 11\nline 12\nline 13\nline 14\nline 15\nline 16\nline 17\nline 18\nline 19\nline 20\nline 21\nline 22\nline 23\nline 24\nchanged 25\nline 26\nline 27\nline 28\nline 29\nline 30\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,6 +1,6 @@\n line 1\n line 2\n-line 3\n+changed 3\n line 4\n line 5\n line 6\n@@ -22,7 +22,7 @@\n line 22\n line 23\n line 24\n-line 25\n+changed 25\n line 26\n line 27\n line 28\n"
  },
  {
    "name": "close changes share a hunk",
    "left": "line 1\nline 2\nline 3\nline 4\nline 5\nline 6\nline 7\nline 8\nline 9\nline 10\nline 11\nline 12\nline 13\nline 14\nline 15\nline 16\nline 17\nline 18\nline 19\nline 20\n",
    "right": "line 1\nline 2\nline 3\nline 4\nchanged 5\nline 6\nline 7\nline 8\nline 9\nline 10\nchanged 11\nline 12\nline 13\nline 14\nline 15\nline 16\nline 17\nline 18\nline 19\nline 20\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -2,13 +2,13 @@\n line 2\n line 3\n line 4\n-line 5\n+changed 5\n line 6\n line 7\n line 8\n line 9\n line 10\n-line 11\n+changed 11\n line 12\n line 13\n line 14\n"
  },
  {
    "name": "changes seven lines apart share a hunk",
    "left": "line 1\nline 2\nline 3\nline 4\nline 5\nline 6\nline 7\nline 8\nline 9\nline 10\nline 11\nline 12\nline 13\nline 14\nline 15\nline 16\nline 17\nline 18\nline 19\nline 20\n",
    "right": "line 1\nline 2\nline 3\nline 4\nchanged 5\nline 6\nline 7\nline 8\nline 9\nline 10\nline 11\nchanged 12\nline 13\nline 14\nline 15\nline 16\nline 17\nline 18\nline 19\nline 20\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -2,14 +2,14 @@\n line 2\n line 3\n line 4\n-line 5\n+changed 5\n line 6\n line 7\n line 8\n line 9\n line 10\n line 11\n-line 12\n+changed 12\n line 13\n line 14\n line 15\n"
  },
  {
    "name": "changes eight lines apart make two hunks",
    "left": "line 1\nline 2\nline 3\nline 4\nline 5\nline 6\nline 7\nline 8\nline 9\nline 10\nline 11\nline 12\nline 13\nline 14\nline 15\nline 16\nline 17\nline 18\nline 19\nline 20\n",
    "right": "line 1\nline 2\nline 3\nline 4\nchanged 5\nline 6\nline 7\nline 8\nline 9\nline 10\nline 11\nline 12\nchanged 13\nline 14\nline 15\nline 16\nline 17\nline 18\nline 19\nline 20\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -2,7 +2,7 @@\n line 2\n line 3\n line 4\n-line 5\n+changed 5\n line 6\n line 7\n line 8\n@@ -10,7 +10,7 @@\n line 10\n line 11\n line 12\n-line 13\n+changed 13\n line 14\n line 15\n line 16\n"
  },
  {
    "name": "no newline at the end of the right side",
    "left": "a\nb\n",
    "right": "a\nb",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,2 +1,2 @@\n a\n-b\n+b\n\\ No newline at end of file\n"
  },
  {
    "name": "no newline at the end of the left side",
    "left": "a\nb",
    "right": "a\nb\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,2 +1,2 @@\n a\n-b\n\\ No newline at end of file\n+b\n"
  },
  {
    "name": "no newline on either side, last line changed",
    "left": "a\nb",
    "right": "a\nc",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,2 +1,2 @@\n a\n-b\n\\ No newline at end of file\n+c\n\\ No newline at end of file\n"
  },
  {
    "name": "no newline on either side, first line changed",
    "left": "a\nb\nc\nd\ne",
    "right": "x\nb\nc\nd\ne",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,4 +1,4 @@\n-a\n+x\n b\n c\n d\n"
  },
  {
    "name": "CRLF lines",
    "left": "one\r\ntwo\r\nthree\r\n",
    "right": "one\r\n2\r\nthree\r\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,3 +1,3 @@\n one\r\n-two\r\n+2\r\n three\r\n"
  },
  {
    "name": "CRLF against LF",
    "left": "one\r\ntwo\r\n",
    "right": "one\ntwo\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,2 +1,2 @@\n-one\r\n-two\r\n+one\n+two\n"
  },
  {
    "name": "unicode",
    "left": "Привет, мир\nemoji 👍🏽\n日本語\n",
    "right": "Привет, мир!\nemoji 👍🏽\n中文\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,3 +1,3 @@\n-Привет, мир\n+Привет, мир!\n emoji 👍🏽\n-日本語\n+中文\n"
  },
  {
    "name": "a function inserted between two",
    "left": "int f() {\n  return 1;\n}\n\nint h() {\n  return 3;\n}\n",
    "right": "int f() {\n  return 1;\n}\n\nint g() {\n  return 2;\n}\n\nint h() {\n  return 3;\n}\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -2,6 +2,10 @@\n   return 1;\n }\n \n+int g() {\n+  return 2;\n+}\n+\n int h() {\n   return 3;\n }\n"
  },
  {
    "name": "a python method inserted",
    "left": "class A:\n    def a(self):\n        return 1\n\n    def c(self):\n        return 3\n",
    "right": "class A:\n    def a(self):\n        return 1\n\n    def b(self):\n        return 2\n\n    def c(self):\n        return 3\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -2,5 +2,8 @@\n     def a(self):\n         return 1\n \n+    def b(self):\n+        return 2\n+\n     def c(self):\n         return 3\n"
  },
  {
    "name": "a paragraph inserted between paragraphs",
    "left": "First paragraph.\n\nThird paragraph.\n\nFourth.\n",
    "right": "First paragraph.\n\nSecond paragraph,\non two lines.\n\nThird paragraph.\n\nFourth.\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,5 +1,8 @@\n First paragraph.\n \n+Second paragraph,\n+on two lines.\n+\n Third paragraph.\n \n Fourth.\n"
  },
  {
    "name": "a nested block removed",
    "left": "if (a) {\n  if (b) {\n    run();\n  }\n  if (c) {\n    stop();\n  }\n}\n",
    "right": "if (a) {\n  if (c) {\n    stop();\n  }\n}\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,7 +1,4 @@\n if (a) {\n-  if (b) {\n-    run();\n-  }\n   if (c) {\n     stop();\n   }\n"
  },
  {
    "name": "a JSON item added",
    "left": "[\n  {\n    \"id\": 1\n  },\n  {\n    \"id\": 2\n  }\n]\n",
    "right": "[\n  {\n    \"id\": 1\n  },\n  {\n    \"id\": 2\n  },\n  {\n    \"id\": 3\n  }\n]\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -4,5 +4,8 @@\n   },\n   {\n     \"id\": 2\n+  },\n+  {\n+    \"id\": 3\n   }\n ]\n"
  },
  {
    "name": "lines moved",
    "left": "import a\nimport b\n\nconst x = 1;\nconst y = 2;\n\nrun(x, y);\n",
    "right": "import b\nimport a\n\nconst y = 2;\nconst x = 1;\n\nrun(x, y);\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,7 +1,7 @@\n-import a\n import b\n+import a\n \n-const x = 1;\n const y = 2;\n+const x = 1;\n \n run(x, y);\n"
  },
  {
    "name": "a config edited in three places",
    "left": "[server]\nhost = localhost\nport = 8080\n\n[db]\nname = app\nuser = admin\npool = 5\n\n[log]\nlevel = info\nfile = app.log\n",
    "right": "[server]\nhost = 0.0.0.0\nport = 8080\n\n[db]\nname = app\nuser = app\npool = 10\ntimeout = 30\n\n[log]\nlevel = debug\nfile = app.log\n",
    "ignoreWhitespace": false,
    "patch": "--- left\n+++ right\n@@ -1,12 +1,13 @@\n [server]\n-host = localhost\n+host = 0.0.0.0\n port = 8080\n \n [db]\n name = app\n-user = admin\n-pool = 5\n+user = app\n+pool = 10\n+timeout = 30\n \n [log]\n-level = info\n+level = debug\n file = app.log\n"
  },
  {
    "name": "only whitespace differs, with -w",
    "left": "a  b\nc\n\td\n",
    "right": "a b\nc\n    d\n",
    "ignoreWhitespace": true,
    "patch": ""
  },
  {
    "name": "whitespace and a real change, with -w",
    "left": "if (x)  {\n  y = 1;\n}\n",
    "right": "if (x) {\n    y = 2;\n}\n",
    "ignoreWhitespace": true,
    "patch": "--- left\n+++ right\n@@ -1,3 +1,3 @@\n if (x)  {\n-  y = 1;\n+    y = 2;\n }\n",
    "git": "--- left\n+++ right\n@@ -1,3 +1,3 @@\n if (x) {\n-  y = 1;\n+    y = 2;\n }\n"
  }
];
