export {
  codeFrame,
  formatJson,
  minifyJson,
  repairJson,
  suggestFixes,
  validateJson,
  type FixRule,
  type FormatOptions,
  type Indent,
  type JsonError,
  type JsonFix,
  type RepairResult,
  type Result,
} from "@web-kit/json-core";
